### Get
GET http://localhost:3001/api/persons

### Create OK
POST http://localhost:3001/api/persons
content-type: application/json

{
  "name": "My name is",
  "number": "1234"
}

### Create no name
POST http://localhost:3001/api/persons
content-type: application/json

{
  "number": "4444"
}

### Create no number 
POST http://localhost:3001/api/persons
content-type: application/json

{
  "name": "My name is"
}

### Update OK
PUT http://localhost:3001/api/persons/693be936b69e8ed64d4336b2
content-type: application/json

{
  "name": "My name is",
  "number": "111-666"
}

### Delete malformed id
DELETE http://localhost:3001/api/persons/2

### Delete missing id
DELETE http://localhost:3001/api/persons/693aa760c7888ed11e183c43

### Delete OK id
DELETE http://localhost:3001/api/persons/693aa760c7888ed11e183c48